repos:
  - repo : local
    hooks :
      - id: black
        name: black
        language: system
        entry: black
        pass_filenames: true
        types: [file, python]
        stages: [commit]

      - id: pylint
        name: pylint
        language: system
        entry: pylint
        pass_filenames: true
        types: [file, python]
        stages: [commit]

      - id: pydocstyle
        name: pydocstyle
        language: system
        entry: pydocstyle --convention=numpy
        pass_filenames: true
        types: [file, python]
        stages: [commit]

      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        stages: [push]
        always_run: true
