repos:
  - repo : local
    hooks :
      - id: black
        name: black
        entry: black
        language: system
        pass_filenames: true
        types: [file, python]
        stages: [commit]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        pass_filenames: true
        types: [file, python]
        stages: [commit]

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [push]
        always_run: true
