repos:
  - repo : local
    hooks :
      - id: black
        name: black
        entry: black
        language: system
        pass_filenames: true
        types: [file, python]
        stages: [commit]
        files: ^README.ipynb$