name: Python Package using Conda

on: [push]

jobs:
  build:

    strategy:
      matrix:
        python_version: ["3.11"]
        os: ["ubuntu-latest"]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file requirements.conda.yaml --name base

    - name : Activate conda env
      run: |
        conda init bash && source ~/.bashrc && conda activate base

    - name: Install TorchTools
      run: |
        pip install -e .

    - name: Format with black
      run: |
        black $(git ls-files torch_tools)

    - name: Lint with Pylint
      run: |
        pylint $(git ls-files torch_tools)

    - name: Test with Pytest
      run: |
        pytest tests

    - name: Lint with Mypy
      run: |
        mypy $(git ls-files torch_tools)

    - name: Lint with Pydocstyle
      run : |
        pydocstyle $(git ls-files torch_tools) --convention=numpy
